name: Docs

run-name: ${{github.actor}} Docs - ${{github.ref_name}}

permissions:
    contents: write

on:
    push:
        paths:
            - "docs/**"
            - "mkdocs.yml"
    pull_request:
        paths:
            - "docs/**"
            - "mkdocs.yml"

    workflow_call:
      inputs:
        deploy:
          required: false
          type: boolean
          default: false

    workflow_dispatch:
      inputs:
        deploy:
          required: false
          type: boolean
          default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
    docs:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Setup uv
            uses: astral-sh/setup-uv@v4
            with:
              version: "latest"

          - name: Install dependencies
            run: uv sync --all-extras --dev

          - name: Build Docs
            run: uv run mkdocs build

          - name: Deploy Docs
            if: inputs.deploy == true
            run: uv run mkdocs gh-deploy --force

