name: Publish PyPI
run-name: ${{github.actor}} is publishing to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        type: string

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  deploy:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: [ci]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install uv
        run: pip install uv

      - name: Set version from release tag
        if: github.event.release.tag_name
        run: |
          VERSION=${{github.event.release.tag_name}}
          uv version ${VERSION#v}

      - name: Set version from input
        if: github.event.inputs.version
        run: |
          VERSION=${{github.event.inputs.version}}
          uv version ${VERSION#v}

      - name: Build package
        run: uv build

      - name: Publish to PyPI
        run: uv publish --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}

  docs:
    name: Deploy Docs
    needs: [deploy]
    uses: ./.github/workflows/docs.yml
    permissions:
      contents: write
    with:
      deploy: true
